// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6E156VXoEUv5t4hz79QDmut5EYlr7ZYA',
    appId: '1:316118035517:web:1fdf4f04e56adbb9f48e54',
    messagingSenderId: '316118035517',
    projectId: 'yksgunlugum-7a0e0',
    authDomain: 'yksgunlugum-7a0e0.firebaseapp.com',
    storageBucket: 'yksgunlugum-7a0e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGBnCVnVp9e_BAehEC98iEY8zxS-HHdc',
    appId: '1:316118035517:android:c0c55b5054188427f48e54',
    messagingSenderId: '316118035517',
    projectId: 'yksgunlugum-7a0e0',
    storageBucket: 'yksgunlugum-7a0e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXZGmw0ExzwGIvOFm_WuwPsfdc7sf-S3Q',
    appId: '1:316118035517:ios:3412b5a79d3720bdf48e54',
    messagingSenderId: '316118035517',
    projectId: 'yksgunlugum-7a0e0',
    storageBucket: 'yksgunlugum-7a0e0.firebasestorage.app',
    iosBundleId: 'com.mkagca.yksgunluk',
  );

}