name: Build iOS IPA

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout kod
      uses: actions/checkout@v4
    
    - name: Flutter kurulumu
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'  # ← BU SATIRI DEĞİŞTİRİN
        channel: 'stable'
    
    - name: Working directory kontrol
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Looking for pubspec.yaml:"
        find . -name "pubspec.yaml" -type f
    
    - name: Flutter doctor ve pub get
      run: |
        # pubspec.yaml dosyasının olduğu dizini bul
        if [ -f "pubspec.yaml" ]; then
          echo "pubspec.yaml found in root directory"
          flutter doctor -v
          flutter pub get
        elif [ -f "flutter_app/pubspec.yaml" ]; then
          echo "pubspec.yaml found in flutter_app directory"
          cd flutter_app
          flutter doctor -v
          flutter pub get
          cd ..
        else
          echo "Searching for Flutter project..."
          FLUTTER_DIR=$(find . -name "pubspec.yaml" -type f | head -1 | xargs dirname)
          if [ ! -z "$FLUTTER_DIR" ]; then
            echo "Found Flutter project in: $FLUTTER_DIR"
            cd "$FLUTTER_DIR"
            flutter doctor -v
            flutter pub get
            cd - > /dev/null
          else
            echo "ERROR: No Flutter project found!"
            exit 1
          fi
        fi
    
    - name: iOS Build
      run: |
        # Flutter projesinin olduğu dizini bul ve build yap
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -type f | head -1 | xargs dirname)
        if [ ! -z "$FLUTTER_DIR" ]; then
          cd "$FLUTTER_DIR"
          flutter build ios --release --no-codesign
          cd - > /dev/null
        else
          echo "ERROR: No Flutter project found for build!"
          exit 1
        fi
    
    - name: IPA oluştur
      run: |
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -type f | head -1 | xargs dirname)
        if [ ! -z "$FLUTTER_DIR" ]; then
          cd "$FLUTTER_DIR"
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r unsigned-app.ipa Payload/
          ls -la
          cd - > /dev/null
        fi
    
    - name: IPA dosyasını yükle
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa-unsigned
        path: |
          **/build/ios/iphoneos/unsigned-app.ipa
        retention-days: 30
